services:
 frontend:
  build:
   context: ./frontend
  container_name: blog-ui
  ports: 
   - 3000:80
  networks:
   - blog-network
  env_file: 
   -  ./frontend/.env

 backend:
  build: 
   context: ./backend
  container_name: blog-backend
  env_file:
   - ./backend/.env
  networks:
   - blog-network

 database: 
  image: mongo
  container_name: blog-datadb
  volumes:
   - ./blog-db/db:/data/db
   - ./blog-db/configdb:/data/configdb
  networks:
   - blog-network 
  

networks: 
 blog-network:  