services:
 frontend:
  build:
   context: ./frontend
  container_name: blog-ui
  ports:
   - 3000:80
  networks:
   - blog-network
  depends_on:
   - backend

 backend:
  build:
   context: ./backend
  container_name: blog-bck
  env_file:
   - ./backend/.env
  networks:
   - blog-network
  depends_on:
   - database

 database:
  image: mongo:7.0
  container_name: blog-db
  volumes:
   - ./blog-db/db:/data/db
   - ./blog-db/configdb:/data/configdb
  networks:
   - blog-network


networks:
 blog-network:
